site/meteor/urls.py
from django.urls import path

from . import views


app_name = 'meteor'
urlpatterns = [
    path('', views.index, name='index'),
    path('more/<str:book_name>', views.more, name='more'),
    path('search/', views.search, name='search'),
    path('cars/', views.cars, name='cars'),
    path('add_book/', views.add_book, name='add_book'),
    path('del_book/', views.del_book, name='del_book'),
    path('buy/', views.buy, name='buy'),
]

site/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('meteor.urls')),
    path('admin/', admin.site.urls),
]

site/meteor/models.py
from django.db import models


# Create your models here.

site/meteor/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse


import sqlite3
from collections import namedtuple
import random
import re


# Create your views here.

car = []

def index(request):
    Entry = namedtuple('Entry', 'id, book_name, pic_url, pub, brief_des, des')
    with sqlite3.connect('meteor/data/db.sqlite') as conn:
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute("""SELECT * FROM books WHERE 
              id in (?, ?, ?, ?, ?);""", random.sample(range(0, 100), 5))
        entries = [Entry(*tuple(entry)) for entry in cur.fetchall()]
    return render(request, 'meteor/index.html', {'entries': entries})


def more(request, book_name):
    with sqlite3.connect('meteor/data/db.sqlite') as conn:
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        cur.execute("""SELECT * FROM books WHERE book_name=(?)""", (book_name,))
        entry = cur.fetchone()
    return render(request, 'meteor/more.html', {'entry': entry})

def search(request):
    book_name = request.POST['book_name']
    return HttpResponseRedirect(reverse('meteor:more', args=(book_name,)))


def cars(request):
    global car
    Book = namedtuple('Book', 'book_name, price')
    with sqlite3.connect('meteor/data/db.sqlite') as conn:
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        books = []
        for index, book in enumerate(car):
            cur.execute("""SELECT book_name, pub FROM books WHERE book_name=(?)""", (book, ))
            book_name, pub =cur.fetchone() # book_name, pub
            books.append(Book(book_name, pub.split('/')[-1].replace('元', '')
                              .replace('NT$', '').replace('CNY', '')
                              .replace('NTD', '')))
    return render(request, 'meteor/cars.html', {'books': books})


def add_book(request):
    global car
    if request.method == 'POST':
        book_name = request.body.decode('utf-8').split('=')[-1]
        car.append(book_name) if book_name not in car else None
    return HttpResponse('Hi, client')

def del_book(request):
    global car
    if request.method == 'POST':
        book_name = request.body.decode('utf-8').split('=')[-1]
        if book_name == '*cleanbook*':
            car.clear()
            return HttpResponseRedirect(reverse('meteor:cars'))
        else:
            car.remove(book_name)
    return HttpResponse('Hi, client')


def buy(request):
    global car
    Book = namedtuple('Book', 'book_name, price')
    with sqlite3.connect('meteor/data/db.sqlite') as conn:
        conn.row_factory = sqlite3.Row
        cur = conn.cursor()
        books = []
        for index, book in enumerate(car):
            cur.execute("""SELECT book_name, pub FROM books WHERE book_name=(?)""", (book,))
            book_name, pub = cur.fetchone()  # book_name, pub
            books.append(Book(book_name, pub.split('/')[-1].replace('元', '')
                              .replace('NT$', '').replace('CNY', '')
                              .replace('NTD', '')))
    total_money = round(sum(float(i.price) for i in books), 2)
    return render(request, 'meteor/buy.html', {'total_money': total_money})

site/meteor/templates/meteor/base_site.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF8">
    <meta name="referrer" content="no-referrer"/>
    <title>I LOVE HTML</title>
    <style>
        * {
            border: 0;
            padding: 0;
            margin: 0;
        }

        html {
            height: 100%;
        }


        body {
            position: relative;
            min-height: 100%;
            background: url("{% static 'meteor/images/muban.png' %}") no-repeat;
            background-size: 100% 100%;
            background-attachment: fixed;
        }

        a {
            text-decoration: none;
            color: white;
        }

        #top {
            width: 100%;
            height: 50px;
            background-color: #222;
            position: fixed;
            top: 0;
        }

        #top div {
            float: left;
            display: inline-block;
        }

        #logo {
            width: 90px;
            height: 50px;
            margin-left: 30px;
            font-size: 30px;
            font-family: "Open Sans", Arial, Helvetica, Sans-Serif;
            color: white;
            line-height: 50px;
        }

        #search {
            width: 320px;
            height: 50px;
            position: absolute;
            left: 300px;
        }

        #search form {
            line-height: 50px;
        }

        #search form input.text {
            width: 240px;
            height: 30px;
            text-indent: 10px;
        }

        #search form input.submit {
            width: 60px;
            height: 30px;
            line-height: 0;
            margin-left: -4px;
            background-color: rgba(255, 255, 255, 0.7);
        }

        #search form input.submit:hover {
            background-color: rgba(255, 255, 255, 0.8);
        }

        #cars {
            position: absolute;
            right: 0;
            font-size: 30px;
            font-family: 'Ubuntu', 'Lucida Grande', 'Lucida Sans Unicode', 'Geneva', 'Verdana', sans-serif;
            width: 100px;
            height: 50px;
            line-height: 50px;
            color: white;
            margin-right: 30px;
        }

        #main {
            width: 600px;
            margin: 60px auto;
        }

        #content {
            width: 600px;
            margin: 20px auto;
        }

        #entry {
            width: 500px;
            height: 320px;
            background-color: rgba(255, 255, 255, 0.7);
        }

        #img {
            width: 220px;
            height: 320px;
        }

        img {
            width: 220px;
            height: 320px;
        }

        #info {
            width: 240px;
            height: 260px;
            margin-left: 20px;
        }

        #info p {
            margin-top: 10px;
        }

        .aa {
            float: left;
        }

        .car_more {
            margin-top: 10px;
            background-color: #00B2BF;
            width: 140px;
            height: 50px;
            color: white;
        }

        .car_more:hover {
            background-color: #00A6AD;
        }

        .btn2 {
            margin-left: -4px;
        }
    </style>

    <script>
        function isEmpty(node_id) {
            var node = document.getElementById(node_id);
            if (node.value == '') {
                alert("输入内容");
                return false;
            }
            return true;
        }
    </script>
</head>
<body>
<div id="top">
    <div id="logo"><a href="{% url 'meteor:index' %}">杂货店</a></div>
    <div id="search">
        <form action="{% url 'meteor:search' %}" method="POST" onsubmit="return isEmpty('book_name')">
            {% csrf_token %}
            <input type="text" name="book_name" id="book_name" class="text" placeholder="输入书名">
            <input type="submit" class="submit" value="搜索">
        </form>
    </div>
    <div id="cars"><a href="{% url 'meteor:cars' %}">购物车</a></div>
</div>
<div id="main">
    {% block content %}{% endblock %}
</div>
</body>
</html>

site/meteor/templates/meteor/buy.html
{% extends "./base_site.html" %}

{% block content %}
    <div id="main_buy">
        <div id="total_money">总计： {{ total_money }}￥</div>
        <form action="#" method="POST" onsubmit="return congratulations()">
            {% csrf_token %}
            <input type="text" name="card_id" placeholder="这里输入您的银行卡号">
            <input type="password" name="password" placeholder="这里输入您的密码">
            <button id="btn_buy">购买</button>
        </form>
    </div>

    <style>
        #main_buy {
            width: 100%;
            height: 500px;
            margin-top: 100px;
            background-color: rgba(255, 255, 255, 0.6);
        }

        #total_money {
            width: 360px;
            height: 100px;
            color: red;
            font-size: 30px;
            margin: 20px auto;
            text-align: center;
            padding-top: 30px;
        }

        #main_buy form input {
            width: 360px;
            height: 50px;
            display: block;
            margin-top: 20px;
            margin-left: 100px;
            text-indent: 10px;
        }

        #btn_buy {
            width: 360px;
            height: 80px;
            background-color: #00B2BF;
            color: white;
            margin-top: 30px;
            margin-left: 100px;
        }

        #btn_buy:hover {
            background-color: #00A6AD;
        }
    </style>

    <script>
        function congratulations() {
            var btn = document.getElementById("btn_buy");
            var div = document.createElement("div");
            div.setAttribute("style", "font-size: 16px; margin-top: 20px;" +
                "margin-left: 120px; color: red;");
            div.innerHTML = "购买成功！欢迎您下次光临本书店!  ";
            var a = document.createElement('a');
            a.setAttribute("href", "{% url 'meteor:index' %}");
            a.innerHTML = "  首页看看?";
            div.appendChild(a);
            btn.parentNode.appendChild(div);

            clean();
            return false;
        }

        function clean() {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304) {
                        return true;
                    } else {
                        alert("Fail to del!");
                        return false;
                    }
                }
            };
            xhr.open('POST', "{% url 'meteor:del_book' %}", true);
            xhr.setRequestHeader('X-CSRFToken', "{{ csrf_token }}");
            xhr.send('book_name=' + '*cleanbook*');
        }
    </script>
{% endblock %}

site/meteor/templates/meteor/cars.html
{% extends "./base_site.html" %}

{% block content %}
    {% if books %}
        {% for book in books %}
            <div class="book">
                <a href="{% url 'meteor:more' book.book_name %}"><p class="name">{{ book.book_name }}</p></a>
                <p class="price">{{ book.price }}元</p>
                <button class="btn" onclick="det(this, '{{ book.book_name }}')">移出购物车</button>
            </div>
            <div class="separator"></div>
        {% endfor %}
        <div id="buy_or_clean">
            <a href="{% url 'meteor:buy' %}">
                <button id="buy" class="btn" onclick="buy()">购买所有</button>
            </a>
            <button id="clean" class="btn" onclick="clean()">清除所有</button>
        </div>
    {% else %}
        <div class="book">
            <p>购物车还没有书呢，去<a href="{% url 'meteor:index' %}">首页</a>看看吧</p>
        </div>
    {% endif %}
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script>
        function det(btn, book_name) {
            $(btn.parentNode).hide(1000);
            $(btn.parentNode).next().hide(1000);

            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304) {
                        return true;
                    } else {
                        alert("Fail to del!");
                        return false;
                    }
                }
            };
            xhr.open('POST', "{% url 'meteor:del_book' %}", true);
            xhr.setRequestHeader('X-CSRFToken', "{{ csrf_token }}");
            xhr.send('book_name=' + book_name);
        }

        function buy() {

        }

        function clean() {
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4) {
                    if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304) {
                        return true;
                    } else {
                        alert("Fail to del!");
                        return false;
                    }
                }
            };
            xhr.open('POST', "{% url 'meteor:del_book' %}", true);
            xhr.setRequestHeader('X-CSRFToken', "{{ csrf_token }}");
            xhr.send('book_name=' + '*cleanbook*');
            $(location).attr('href', "{% url 'meteor:cars' %}");

        }
    </script>
    <style>
        .book {
            width: 600px;
            height: 70px;
            background-color: rgba(255, 255, 255, 0.7);
            margin: 0 auto;
        }

        .book p {
            display: inline;
            margin-left: 20px;
            line-height: 70px;
            float: left;
        }

        .book p a, .book a {
            color: dodgerblue;
        }

        .name {
            width: 230px;
            height: 50px;
        }

        .price {
            width: 100px;
            height: 50px;
            color: red;
        }

        .separator {
            width: 100%;
            height: 10px;
        }

        .btn {
            width: 100px;
            height: 100%;
            float: right;
            background-color: #00B2BF;
            color: white;
        }

        .btn:hover {
            background-color: #00A6AD;
        }

        #buy_or_clean {
            width: 600px;
            height: 70px;
            margin: 30px auto;
        }

        #buy {
            width: 300px;
        }

        #clean {
            width: 300px;
        }
    </style>
{% endblock %}

site/meteor/templates/meteor/index.html
{% extends "./base_site.html" %}

{% block content %}
    {% if entries %}
        {% for entry in entries %}
            <div id="content">
                <div id="entry">
                    <div id="img" class="aa"><img src="{{ entry.pic_url }}"></div>
                    <div id="info" class="aa">
                        <p>书名： {{ entry.book_name }}</p>
                        <p>作者: {{ entry.pub }}</p>
                        <p>简介: {{ entry.brief_des }}</p>
                    </div>
                    <div>
                    <button class="car_more" onclick="return addCars(this, '{{ entry.book_name }}');">加入购物车</button>
                    <a href="{% url 'meteor:more' entry.book_name %}"><button class="car_more btn2">更多</button></a>
                    </div>
                </div>
            </div>
            <p></p>
        {% endfor %}
    {% endif %}
    <script>
        function addCars(btn, book_name){
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function() {
                if (xhr.readyState === 4) {
                    if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304) {
                        btn.innerHTML = "已加入";
                        return true;
                    } else {
                        alert("Fail to add!");
                        return false;
                    }
                }
            };
            xhr.open('POST', "{% url 'meteor:add_book' %}", true);
            xhr.setRequestHeader('X-CSRFToken', "{{ csrf_token }}");
            xhr.send('book_name=' + book_name);
        }
    </script>
{% endblock %}

site/meteor/templates/meteor/more.html
{% extends "./base_site.html" %}

{% block content %}
    <style>
        #more_main {
            width: 800px;
            height: 100%;
            margin: 80px auto;
            background-color: rgba(255, 255, 255, 0.7);
            color: white;
        }

        #img {
			width: 200px;
			height: 360px;
			margin-right: 10px;
		}
		
		#img img {
            width: 200px;
            margin-right: 10px;
        }

        #more_main div {
            float: left;
        }

        p {
            width: 600px;
        }

        #info a {
            color: dodgerblue;
        }

		#add_car {
			width: 200px;
			height: 40px;
			background-color: #00B2BF;
			color: white;
		}

		#add_car:hover {
			background-color: #00A6AD;
		}
    </style>
	<script>
		function add_car(btn, book_name) {
			btn.innerHTML = "已加入";
			var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function() {
                if (xhr.readyState === 4) {
                    if ((xhr.status >= 200 && xhr.status < 300) || xhr.status == 304) {
                        btn.innerHTML = "已加入";
                        return true;
                    } else {
                        alert("Fail to add!");
                        return false;
                    }
                }
            };
            xhr.open('POST', "{% url 'meteor:add_book' %}", true);
            xhr.setRequestHeader('X-CSRFToken', "{{ csrf_token }}");
            xhr.send('book_name=' + book_name);
		}
	</script>
    <div id="more_main">
        <div id="info">
            {% if entry %}
                <p>书名： {{ entry.book_name }}</p>
                <p>作者: {{ entry.pub }}</p>
                <p>简介: {{ entry.brief_des }}</p>
                <div id="img">
                    <img src="{{ entry.pic_url }}">
					<button id="add_car" onclick="return add_car(this, '{{ entry.book_name }}')">加入购物车</button>
                </div>
                <p>详细内容: {{ entry.des }}</p>
            {% else %}
                <p>没有找到这本书</p>
                <a href="{% url 'meteor:index' %}">返回首页？</a>
            {% endif %}
        </div>
    </div>
{% endblock %}